name: Scrap AW

on:
  schedule:
    - cron: '0 0 * * *' # tous les jours à minuit
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run script
        run: |
          python3 script/scrapper.py --debug

      - name: Display JSON content
        run: cat jobs.json

      - name: Commit and push
        run: |
          git config --local user.email "leandro.rsstti@gmail.com"
          git config --local user.name "LeandroRSSTT"
          git add jobs.json
          git commit -m "Update jobs.json" -a
          git push https://${{ secrets.GH_PAT }}@github.com/LeandroRSSTT/ItJobFinder.git
